# Generated by Django 4.0.4 on 2022-04-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_newuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='code',
            field=models.CharField(default='+91', max_length=10),
        ),
    ]
