# Generated by Django 4.0.2 on 2022-04-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0004_newuser_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientIdMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=10)),
                ('token_id', models.CharField(max_length=10, null=True)),
                ('special_ethan_token', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DbInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=10)),
                ('db_name', models.CharField(max_length=30)),
                ('db_host', models.CharField(max_length=30)),
                ('db_port', models.CharField(max_length=30)),
                ('db_user', models.CharField(max_length=30)),
                ('db_password', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='newuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
