# Generated by Django 4.0.2 on 2022-05-02 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_clientidmapping_dbinformation_alter_newuser_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('referance_id', models.AutoField(primary_key=True, serialize=False)),
                ('ref_type', models.CharField(max_length=100)),
                ('field1', models.CharField(max_length=100)),
                ('field2', models.CharField(max_length=100)),
                ('field3', models.CharField(max_length=100)),
                ('field4', models.CharField(max_length=100)),
                ('field5', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='clientidmapping',
            old_name='special_ethan_token',
            new_name='ethan_token',
        ),
        migrations.RemoveField(
            model_name='clientidmapping',
            name='token_id',
        ),
        migrations.RemoveField(
            model_name='dbinformation',
            name='db_host',
        ),
        migrations.RemoveField(
            model_name='dbinformation',
            name='db_name',
        ),
        migrations.RemoveField(
            model_name='dbinformation',
            name='db_password',
        ),
        migrations.RemoveField(
            model_name='dbinformation',
            name='db_port',
        ),
        migrations.RemoveField(
            model_name='dbinformation',
            name='db_user',
        ),
        migrations.AddField(
            model_name='dbinformation',
            name='referance_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.reference'),
        ),
    ]
