# Generated by Django 4.0.2 on 2022-05-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='field2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='field3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='field4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='field5',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
