# Generated by Django 4.0.4 on 2022-06-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_reference_field2_alter_reference_field3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tableau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitename', models.CharField(max_length=150, null=True)),
                ('password', models.CharField(max_length=150, null=True)),
                ('user_id', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TableauConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=150, null=True)),
                ('tableau_id', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='clientidmapping',
            name='ethan_token',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
